include("eternity2/eternity2.jl")
include("eternity2/experiment_config.jl")
include("eternity2/model_config.jl")
include("eternity2/models.jl")
include("eternity2/rewards.jl")

include("graphcoloring/coloring_config.jl")
include("graphcoloring/coloring_models.jl")
include("graphcoloring/coloring_pipeline.jl")
include("graphcoloring/coloring_rewards.jl")
include("graphcoloring/graphcoloring.jl")

include("latin/agent_config.jl")
include("latin/agents.jl")
include("latin/latin_config.jl")
include("latin/featurization.jl")
include("latin/latin.jl")
include("latin/utils.jl")
include("latin/rewards.jl")

include("kep/kep_config.jl")
include("kep/kidneyexchange.jl")

include("knapsack/features.jl")
include("knapsack/models.jl")
include("knapsack/model_config.jl")
include("knapsack/rewards.jl")
include("knapsack/experiment_setup.jl")
include("knapsack/knapsack.jl")