include("eternity2/eternity2.jl")
include("eternity2/experiment_config.jl")
include("eternity2/model_config.jl")
include("eternity2/models.jl")
include("eternity2/rewards.jl")

include("graph_coloring/coloring_config.jl")
include("graph_coloring/coloring_models.jl")
include("graph_coloring/coloring_pipeline.jl")
include("graph_coloring/coloring_rewards.jl")
include("graph_coloring/graph_coloring.jl")

include("latin/agent_config.jl")
include("latin/agents.jl")
include("latin/latin_config.jl")
include("latin/featurization.jl")
include("latin/latin.jl")
include("latin/utils.jl")
include("latin/rewards.jl")

include("kidney_exchange/kidney_exchange_config.jl")
include("kidney_exchange/kidney_exchange.jl")

include("knapsack/features.jl")
include("knapsack/models.jl")
include("knapsack/model_config.jl")
include("knapsack/rewards.jl")
include("knapsack/experiment_setup.jl")
include("knapsack/knapsack.jl")

include("nqueens/agents.jl")
include("nqueens/model_config.jl")
include("nqueens/nqueens_config.jl")
include("nqueens/nqueens.jl")
include("nqueens/rewards.jl")
include("nqueens/utils.jl")

include("tsptw/agents.jl")
include("tsptw/heuristics.jl")
include("tsptw/utils.jl")
include("tsptw/tsptw.jl")
include("tsptw/tsptw_config.jl")

include("utils/save_metrics.jl")